### ISSUE TITLE
[feature-request] Configurable poll time

### ISSUE THREAD

**Issue by landerlini** [viktorholk/push-notifications-api#1]
Thanks for this super insteresting project. 
The android app works nicely, but it is a bit too greedy on battery, probably because the rate of polling requests is quite high. 
This is fantastic for development, but for my application I would be happy to poll once per minute or even less to preserve my battery charge.

It would be great if one could modify the polling time together with the address from the app configuration page.

**Comment by viktorholk** [comment]
Thank you for the feature request!
I haven't thought of that when i wrote it and yes the 5 seconds pooling time is definitely too extreme.
I will look on implementing it.

**Comment by viktorholk** [comment]
Unfortunately, I have lost my key store file for updating the app on Google Play. I will have to republish the application.
You will have to download the latest APK from [releases](https://github.com/viktorholk/push-notifications-api/releases), for now.
