### ISSUE TITLE
app executed in background

### ISSUE THREAD

**Issue by ZennDC** [viktorholk/push-notifications-api#11]
is it possible to remove the notification that says the app is being executed in the background

**Comment by viktorholk** [comment]
Android limitations with how the background service works

This is only possible with Android 13 (API level 33) and above
https://developer.android.com/develop/background-work/services/foreground-services#user-dismiss-notification

What Android version are you running?

**Comment by ZennDC** [comment]
Yeah i found it thx, and version 14 btw. The other updates work great btw.
