### ISSUE TITLE
No Config File

### ISSUE THREAD

**Issue by Taranath91** [viktorholk/push-notifications-api#5]
Hello, I have an issue to start the script

if I start the script it says no config file found but it already exists. 
and I think the script would create a if no exist.

but it doesn't work.

I have manually removed the config in the script and added it hardcoded. But in all chnages it says wrong syntax 

Mit freundlichen Grüßen

Tara

**Comment by viktorholk** [comment]
Hi Tara,

Did you resolve your issue?
