### ISSUE TITLE
[Feature]: Server-Sent Events (SSE)

### ISSUE THREAD

**Issue by 7heMech** [viktorholk/push-notifications-api#7]
You could add [SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) support, this would improve real-time communication and reduce overhead

Edit: I can implement a simple server example in JS/Python.

**Comment by viktorholk** [comment]
Yes!
I was looking shortly into improving the real-time communication and ended on WebSockets but figured it would impact the battery too much.

SSE seems much more lightweight so I will look into that

Thanks
